In [14]:
import numpy as np
import sympy as sy
from sympy import *
from sympy.abc import x
import matplotlib.pyplot as plt

In [15]:
x,y,z=sy.symbols('x,y,z')
print('Matriz A')
A=np.array([[3,7,8],[9,4,2],[1,12,6]])
display(A)
print('Matriz F')
F=np.array([1,2,3])
display(F)
print('Matriz de variables')
X=np.array([x,y,z])
display(X)
AXF=np.array(A*X)
display(AXF)

Matriz A


array([[ 3,  7,  8],
       [ 9,  4,  2],
       [ 1, 12,  6]])

Matriz F


array([1, 2, 3])

Matriz de variables


array([x, y, z], dtype=object)

array([[3*x, 7*y, 8*z],
       [9*x, 4*y, 2*z],
       [x, 12*y, 6*z]], dtype=object)

In [16]:
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range(j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
    return U,G


In [17]:
gauss(A,F)

(array([[  3,   7,   8],
        [  0, -17, -22],
        [  0,   0,  -8]]),
 array([ 1, -1,  1]))