In [10]:
import numpy as np
import sympy as sy
from sympy import *
from sympy.abc import x
import matplotlib.pyplot as plt

In [11]:
x,y,z=sy.symbols('x,y,z')
print('Matriz A')
A=np.array([[3,7,8],[9,4,2],[1,12,6]])
display(A)
print('Matriz F')
F=np.array([13,22,8])
display(F)

Matriz A


array([[ 3,  7,  8],
       [ 9,  4,  2],
       [ 1, 12,  6]])

Matriz F


array([13, 22,  8])

In [12]:
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range(j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
    return U,G


In [18]:
gauss(A,F)

(array([[  3,   7,   8],
        [  0, -17, -22],
        [  0,   0,  -8]]),
 array([ 13, -17,  -6]))

In [21]:
U=gauss(A,F)[0]
print(U)
G=gauss(A,F)[1]
print(G)

def solrev(U,G):
    C=0
    n= G.size
    X= np.zeros(n)
    for i in reversed(range(n)):
        if i==n-1:
            X[i]=(G[i])/(U[i,i])
            continue
        else:
            for j in range (i+1,n):
                C+=U[i,j]*X[j]
            X[i]=(G[i]/U[i,i])-(1/U[i,i])*C
            C=0
    return X

[[  3   7   8]
 [  0 -17 -22]
 [  0   0  -8]]
[ 13 -17  -6]


In [22]:
solrev(U,G)

array([2.26470588, 0.02941176, 0.75      ])